server:
  port: 8888
  
spring:
  application:
    name: ms-admin-config-server

#Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server: 
        native:
          searchLocations: file:///C:/AmbDesarrollo/CURS-000116-ARQMS116/ms-administracion-data-config

# Acuator
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true   